from model import Word
from database import db

def seedData():

    WORDS = [
    "ABOUT","ABOVE","ABUSE","ACTOR","ACUTE","ADMIT","ADOPT","ADORE","ADULT","AFTER",
    "AGAIN","AGENT","AGREE","AHEAD","ALARM","ALBUM","ALERT","ALIEN","ALIGN","ALIVE",
    "ALLOW","ALONE","ALONG","ALTER","AMONG","ANGER","ANGLE","ANGRY","APART","APPLE",
    "APPLY","ARENA","ARGUE","ARISE","ARRAY","ASIDE","ASSET","AUDIO","AVOID","AWAKE",
    "BADLY","BAKER","BASIC","BASIS","BEACH","BEGAN","BEGIN","BEGUN","BEING","BELOW",
    "BENCH","BILLY","BIRTH","BLACK","BLAME","BLIND","BLOCK","BLOOD","BOARD","BOOST",
    "BOOTH","BOUND","BRAIN","BRAND","BREAD","BREAK","BRICK","BRIEF","BRING","BROAD",
    "BROWN","BUILD","BUILT","BUYER","CABLE","CALIF","CARRY","CATCH","CAUSE","CHAIN",
    "CHAIR","CHART","CHASE","CHEAP","CHECK","CHEST","CHIEF","CHILD","CHOIR","CHOOSE",
    "CIVIL","CLAIM","CLASS","CLEAN","CLEAR","CLICK","CLOCK","CLOSE","COACH","COAST",
    "COULD","COUNT","COURT","COVER","CRACK","CRAFT","CRASH","CRIME","CROSS","CROWD",
    "CROWN","CURVE","CYCLE","DAILY","DANCE","DATED","DEALT","DEATH","DEBUT","DELAY",
    "DEPTH","DOING","DOUBT","DOZEN","DRAFT","DRAMA","DRAWN","DREAM","DRESS","DRINK",
    "DRIVE","DROVE","DYING","EARLY","EARTH","EIGHT","ELDER","ELECT","EMPTY","ENEMY",
    "ENJOY","ENTER","ENTRY","EQUAL","ERROR","EVENT","EVERY","EXACT","EXIST","EXTRA",
    "FAITH","FALSE","FAULT","FIBER","FIELD","FIFTH","FIFTY","FIGHT","FINAL","FIRST",
    "FIXED","FLASH","FLEET","FLOOR","FLUID","FOCUS","FORCE","FORTH","FORTY","FORUM",
    "FOUND","FRAME","FRANK","FRAUD","FRESH","FRONT","FRUIT","FULLY","FUNNY","GIANT",
    "GIVEN","GLASS","GLOBE","GOING","GRACE","GRADE","GRAND","GRANT","GRASS","GREAT",
    "GREEN","GROSS","GROUP","GROWN","GUARD","GUESS","GUEST","GUIDE","HAPPY","HARRY",
    "HEART","HEAVY","HENCE","HORSE","HOTEL","HOUSE","HUMAN","IDEAL","IMAGE","INDEX",
    "INNER","INPUT","ISSUE","JAPAN","JIMMY","JOINT","JUDGE","KNOWN","LABEL","LARGE",
    "LASER","LATER","LAUGH","LAYER","LEARN","LEASE","LEAST","LEAVE","LEGAL","LEVEL",
    "LIGHT","LIMIT","LOCAL","LOGIC","LOOSE","LOWER","LUCKY","LUNCH","MAGIC","MAJOR",
    "MAKER","MARCH","MATCH","MAYBE","MEANS","MEDIA","METAL","MIGHT","MINOR","MINUS",
    "MIXED","MODEL","MONEY","MONTH","MORAL","MOTOR","MOUNT","MOUSE","MOUTH","MOVIE",
    "MUSIC","NAKED","NASTY","NEEDS","NEVER","NEWLY","NIGHT","NOISE","NORTH","NOVEL",
    "NURSE","OCCUR","OCEAN","OFFER","OFTEN","ORDER","OTHER","OUGHT","PAINT","PANEL",
    "PAPER","PARTY","PEACE","PHASE","PHONE","PHOTO","PIECE","PILOT","PITCH","PLACE",
    "PLAIN","PLANE","PLANT","PLATE","POINT","POUND","POWER","PRESS","PRICE","PRIDE",
    "PRIME","PRINT","PRIOR","PRIZE","PROOF","PROUD","PROVE","QUEEN","QUICK","QUIET",
    "RADIO","RAISE","RANGE","RAPID","RATIO","REACH","READY","REFER","RIGHT","RIVER",
    "ROUGH","ROUND","ROUTE","ROYAL","RURAL","SCALE","SCENE","SCOPE","SCORE","SENSE",
    "SERVE","SEVEN","SHALL","SHAPE","SHARE","SHARP","SHEET","SHELF","SHIFT","SHINE",
    "SHIRT","SHOCK","SHOOT","SHORT","SHOWN","SIGHT","SINCE","SIXTH","SKILL","SLEEP",
    "SLIDE","SMALL","SMART","SMILE","SMOKE","SOLID","SOLVE","SORRY","SOUND","SOUTH",
    "SPACE","SPARE","SPEAK","SPEED","SPEND","SPENT","SPLIT","SPOKE","SPORT","STAFF",
    "STAGE","STAKE","STAND","START","STATE","STEEL","STICK","STILL","STOCK","STONE",
    "STORE","STORM","STORY","STRIP","STUCK","STUDY","STUFF","STYLE","SUGAR","SUITE",
    "SUPER","SWEET","TABLE","TAKEN","TASTE","TEACH","TEETH","TEXAS","THANK","THEFT",
    "THEIR","THEME","THERE","THICK","THING","THINK","THIRD","THOSE","THREE","THROW",
    "TIGHT","TIMES","TIRED","TITLE","TODAY","TOPIC","TOTAL","TOUCH","TOUGH","TOWER",
    "TRACK","TRADE","TRAIN","TREAT","TREND","TRIAL","TRIED","TRUCK","TRULY","TRUST",
    "TRUTH","TWICE","UNDER","UNDUE","UNION","UNITY","UNTIL","UPPER","UPSET","URBAN",
    "USAGE","USUAL","VALID","VALUE","VIDEO","VISIT","VITAL","VOICE","WASTE",
    "WATCH","WATER","WHEEL","WHERE","WHILE","WHITE","WHOLE","WHOSE","WOMAN",
    "WORLD","WORRY","WORTH","WOULD","WRITE","WRONG","YOUNG"
    ]

    antal = db.session.query(Word).count()

    if antal >= len(WORDS):
        return
    
    for w in WORDS:

        # exists = db.session.query(Word.id).filter_by(word=w).first()
        # if exists:
        #     continue

        ord = Word()
        ord.word=w
        db.session.add(ord)

    db.session.commit()