"""init

Revision ID: 257fba206ae9
Revises: 
Create Date: 2026-02-03 15:22:32.127762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257fba206ae9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=10), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_words')),
    sa.UniqueConstraint('word', name=op.f('uq_words_word'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    # ### end Alembic commands ###
