"""updated models

Revision ID: 42baaeb78035
Revises: 257fba206ae9
Create Date: 2026-02-10 11:26:44.985166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42baaeb78035'
down_revision = '257fba206ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(length=25), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'WON', 'LOST', name='statustype'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name=op.f('fk_games_word_id_words')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_table('guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('guess', sa.String(length=10), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_guesses_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guesses'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guesses')
    op.drop_table('games')
    # ### end Alembic commands ###
